---
  - name: "Installing Retro Pie and UV4L on Raspbian"
    hosts: localhost
    connection: local 
    tasks:


    - name: Add UV4L project keys
      ansible.builtin.apt_key:
        url: https://www.linux-projects.org/listing/uv4l_repo/lpkey.asc
        state: present
    - name: Add UV4L project repository
      ansible.builtin.apt_repository:
        repo: deb https://www.linux-projects.org/listing/uv4l_repo/raspbian/stretch stretch main
        state: present

    - name: "Install UV4l"
      package: 
        name: 
          - uv4l 
          - uv4l-raspidisp 
          - uv4l-raspidisp-extras 
          - uv4l-server
          - uv4l-webrtc
          - uv4l-demos
        state: present

    - name: "Add snd-aloop to /etc/modules"
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: snd-aloop
        create: yes
    - name: 'Configure ALSA'
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/alsa-base.conf
        line: options snd-aloop index=1
        create: yes
        state: present

    - name: Recursively remove directory
        ansible.builtin.file:
        path: ~/.asoundrc
        state: absent

    - name: Download asound.conf
      get_url:
        url: https://www.linux-projects.org/home/wp-content/uploads/2019/03/asound.conf
        dest: /etc/asound.conf
        mode: '0440'

    - name: Restart network service for interface eth0
       ansible.builtin.service:
         name: alsa-restore
         state: restarted


    - name: Download raspberry pi display.conf
      get_url:
        url: https://www.linux-projects.org/home/wp-content/uploads/2019/03/uv4l-raspidisp.conf
        dest: /etc/uv4l/uv4l-raspidisp.conf
        mode: '0440'


